### ISSUE TITLE
This overides 'iskeyword' for all filetypes.

### ISSUE THREAD

**Issue by alex-ross** [gko/vim-coloresque#20]
At  `after/syntax/css/vim-coloresque.vim:125`  you will find these rows.

``` viml
:set isk+=-
:set isk+=#
:set isk+=.
```

This actually overides `iskeyword` in all my `filetypes` and thats not what i expected. Motions and syntax highlighting becomes very different in example ruby and javascript where i expect `.` to actually break the word.

**Comment by agirorn** [comment]
@gorodinskiy can you please just accept some of the patches or comment on them?

**Comment by agirorn** [comment]
Or just remove them from this plugin https://github.com/gorodinskiy/vim-coloresque/pull/25

**Comment by faceleg** [comment]
Seconded, I can't use this plugin until this is fixed, it breaks `w` movements along "dotted" JSON objects in JS, e.g.

`some.object.property`, `w` just jumps from the `s` to the `y`.

**Comment by dawnofthedev** [comment]
This is an example of why I regret using plugins. You need to document this clearly until fixed otherwise you are wasting a lot of people's time trying to 'fix' their configuration.

**Comment by craigp** [comment]
Just discovered that it was this plugin that was doing this to me as well, was driving me insane

**Comment by agirorn** [comment]
More than 2 years have passed since any code has been committed to this repo so I think it time to consider it dead.

**Comment by renstrom** [comment]
As an alternative, https://github.com/ap/vim-css-color seems to be maintained.

**Comment by iamcco** [comment]
The same issuse

**Comment by griffinqiu** [comment]
The same issue

**Comment by hbarcelos** [comment]
Welcome to 2020. I'm facing this issue if I use this alongside [`styled-components/vim-styled-components`](https://github.com/styled-components/vim-styled-components).

More specifically, `vim-styled-components` [includes all CSS syntax](https://github.com/hbarcelos/vim-styled-components/blob/main/after/syntax/javascript.vim#L21-L28) files in JavaScript ant TypeScript files:

```vim
" this is only possible on vim version above 7
if v:version >= 700
  try
    syn include @CSS3 syntax/css/*.vim
  catch
  endtry
endif
```

The `word` text object gets messed up with.
