### ISSUE TITLE
Some colors don't work properly

### ISSUE THREAD

**Issue by paulsoh** [gko/vim-coloresque#35]
![image](https://cloud.githubusercontent.com/assets/18063110/24485577/532b6880-1540-11e7-861d-2030bcb2a4c4.png)

If you look at my screenshot, it seems like only colors in strings and #ffffff are the only ones working
Anyone struggle with this issue?

**Comment by anoopd** [comment]
@paulsoh i just can't replicate your error ....... in scss it is working just fine .
![screen shot 2017-04-05 at 9 13 08 am](https://cloud.githubusercontent.com/assets/925418/24688855/83648e10-19e0-11e7-966b-d12d70c12dd6.png)

**Comment by gko** [comment]
@paulsoh can you recheck:
![image](https://user-images.githubusercontent.com/1726487/80914618-e5c2c800-8d4c-11ea-83df-88f7e4c27c4e.png)

I think it was an issue with `termguicolors`
